name: CI

on:
  merge_group:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    permissions:
      # Required to checkout the code
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v7
        name: Cache build output
        with:
          retention-days: 1
          name: build-output-${{ github.run_id }}
          path: |
            dist/

  coverage:
    permissions:
      # Required to checkout the code
      contents: read
    name: Test and report coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run coverage

  test:
    needs: [build, coverage]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run the testing suite on each major OS with the latest LTS release of Node.js
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ["22.x", "24.x", "26.x"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
